services: 
  storage:
    image: redis
    volumes:
      - ./data:/data
  counter:
    image: ddefo25/counter:1.0.0
    environment: 
      - PORT=8888
      - REDIS_URL=redis://storage
    expose:
      - 8888
    depends_on:
      - storage
  library:
    image: ddefo25/library-docker:1.0.0
    volumes:
      - ./library/books:/app/books
    ports: 
      - 80:8989
    environment: 
      - PORT=8989
      - COUNTER_URL=http://counter:8888/counter
      - BOOKS_DIR=/app
    depends_on:
      - counter
      